version: '3.8'

services:
  app:
    image: node:14
    container_name: my_app
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/taskdb?authSource=admin
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
